### ISSUE TITLE
Fails with the latest version of stylelint

### ISSUE THREAD

**Issue by ismay** [suitcss/stylelint-config-suitcss#14]
Because of this deprecated rule: https://github.com/suitcss/stylelint-config-suitcss/blob/master/index.js#L58

See error here: https://travis-ci.org/ismay/ismay.github.io/builds/116449021#L1663

**Comment by dryoma** [comment]
Actually, not just `rule-no-shorthand-property-overrides`, but also `rule-properties-order` and `rule-trailing-semicolon` (stylelint v. 5.0.1)

**Comment by ntwb** [comment]
@dryoma Correct, all 3 are fixed in #15

**Comment by dryoma** [comment]
Great, thanks!

**Comment by simonsmith** [comment]
Published in `5.0.0`
