### ISSUE TITLE
Release stylelint 7.0 compatible config

### ISSUE THREAD

**Issue by jeddy3** [suitcss/stylelint-config-suitcss#22]
@simonsmith I'm going to prepare a 7.0 compatible release for you :)

I know it feels like stylelint releases are coming thick and fast, but it's been 4 months since the last major release.

This new release is significant in that a lot of work has gone into making the linter more sustainable i.e. putting in place systems to empower the community to build plugins and processors, rather than have these volatile features in the core. Hopefully this will slow down the pace of stylelint releases (especially major ones) even further. I think most of the contributors are looking forward to a little breather as well now that `7.0.0` is out of the door :)

**Comment by simonsmith** [comment]
@jeddy3 Thanks! Yeah, I've started to lose track of the releases so I appreciate you taking care of that. :)
