### ISSUE TITLE
getting odd stylelint output `undefined [undefined]` when suitcss runs

### ISSUE THREAD

**Issue by danalloway** [suitcss/stylelint-config-suitcss#24]
the only things in my `app.css` file are imports

```
@import "suitcss-base";
@import "suitcss-utils";
@import "theme.css";
@import "theme-map.css";
```

any suggestions on how to silence or fix these would be appreciated.
will update if I discover where I have gone wrong here.

thanks!

![screen shot 2016-11-11 at 12 15 09 pm](https://cloud.githubusercontent.com/assets/2057295/20223662/989e489c-a808-11e6-8e7e-4e46cae29497.png)

**Comment by briandrum** [comment]
Any chance you are using `postcss-inline-svg`?

https://github.com/TrySound/postcss-inline-svg/issues/32

**Comment by danalloway** [comment]
good question!
I checked and I'm not requiring that, nor is it loaded from any dependancy I can see... the search continues

**Comment by danalloway** [comment]
yep, that fixed it!
closing this and opening up an issue over at suitcss-preprocessor

thanks @briandrum
