### ISSUE TITLE
Update peer dependency now that stylelint 8.x.x is released

### ISSUE THREAD

**Issue by patsissons** [suitcss/stylelint-config-suitcss#30]

**Comment by ntwb** [comment]
stylelint dependency should be updated at the same time, or before even 😏

**Comment by jeddy3** [comment]
Done in https://github.com/suitcss/stylelint-config-suitcss/pull/31 and released as `12.0.0`.

@patsissons Thanks for the report.
@elyseholladay Thanks again for the PR.
