### ISSUE TITLE
Update stylelint-suitcss and stylelint-order

### ISSUE THREAD

**Issue by vidhem** [suitcss/stylelint-config-suitcss#32]
stylelint-config-suitcss uses stylelint v8 in peer dependencies but the versions used for stylelint-suitcss and stylelint-order still use stylelint v7 which lead to multiple stylelint libraries (both v7 and v8) present in node_modules.

This causes problems in a project I'm working on with a big dependency chain. 

Update the versions as follows
- **stylelint-suitcss** : v2.0.0 (released after [this PR](https://github.com/suitcss/stylelint-suitcss/issues/1))
- **stylelint-order** : ~~v0.8.0~~ v0.7.0 (v0.8 drops support for Node 4/5. Sticking to 0.7 to not have a breaking change).

**Comment by jeddy3** [comment]
Done in https://github.com/suitcss/stylelint-config-suitcss/pull/33

Released as `13.0.0`.

**Comment by vidhem** [comment]
Thanks @jeddy3 for the quick action!
