### ISSUE TITLE
Move this repo to the SuitCSS org

### ISSUE THREAD

**Issue by jeddy3** [suitcss/stylelint-config-suitcss#5]
@simonsmith We're freeing up the stylelint org to focus on stylelint as a tool rather than the configs. As such we intend to move the SuitCSS, Wordpress, and CSS Recipes configs out of the org. I thought the [SuitCSS org](https://github.com/suitcss) would make a good home for this repo as you'll be using it to enforce the [SuitCSS code style](https://github.com/suitcss/suit/blob/master/doc/STYLE.md) on the components. What do you think?

**Comment by simonsmith** [comment]
Makes sense to me

:+1:

**Comment by jeddy3** [comment]
Perfect. It's on its way over now.

**Comment by jeddy3** [comment]
@simonsmith Oh hang on, it [looks like](https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations) either you'll need to be a admin within the stylelint org and do the transfer. Or you need to temporarily grant me admin/owner access to the suit org and I'll do it. Which is best for you?

**Comment by simonsmith** [comment]
How strange. Either works I guess. Maybe add me in there and I'll do it now?

**Comment by jeddy3** [comment]
Done :)

**Comment by simonsmith** [comment]
All done!

**Comment by jeddy3** [comment]
Fantastic. I've granted you npm access too.

Thanks for your help with the transfer Simon. It's much appreciated :)

**Comment by simonsmith** [comment]
No problem, thanks for the config!
