### ISSUE TITLE
Update Appveyor CI

### ISSUE THREAD

**Issue by ntwb** [suitcss/stylelint-config-suitcss#7]
- [x] Update the AppVeyor URL in `README.MD` from `stylelint/stylelint-config-suitcss` to `suitcss/stylelint-config-suitcss`

- [x] Update the AppVeyor repo configuration from `stylelint/stylelint-config-suitcss` to `suitcss/stylelint-config-suitcss` via https://ci.appveyor.com/project/stylelint/stylelint-config-suitcss/settings

**Comment by jeddy3** [comment]
> Update the AppVeyor repo configuration

I've just deleted the project from the stylelint appveyor org. Hopefully you'll now be able to recreate it under either suitcss or your own account @simonsmith, which should give you access to the setting :)

**Comment by ntwb** [comment]
• I've deleted from GitHub the previous AppVeyor webhook for https://github.com/ntwb/stylelint-config-wordpress as changing the repo URL on AppVeyor would not work
• I've now also removed `stylelint-config-wordpress` entirely from AppVeyor
• Each time I try to add `ntwb/stylelint-config-wordpress` to AppVeyor it adds the previous repo `stylelint/stylelint-config-wordpress` and then errors with "Repo not found"

I'm about to send the above of to AppVeyor asking them to flush their cache or a fix, will keep you posted with their reply

**Comment by simonsmith** [comment]
Thanks for this, I'll give it a look this weekend

**Comment by simonsmith** [comment]
@jeddy3 How did you add login as the stylelint org for AppVeyor? It only seems to let me in as a personal user

**Comment by jeddy3** [comment]
I think maybe my personal user is called `stylelint`, and there isn't actually a stylelint org. Sorry for the confusing you... I think I confused myself a little when I setup the appveyor stuff :)

**Comment by simonsmith** [comment]
Ah got you :)

**Comment by simonsmith** [comment]
This seems to be working on each commit now. Thanks for the help chaps
